version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: react-nginx
    ports:
      - '80:80'
    restart: on-failure
    depends_on:
      - go-app

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: go-final
    ports:
      - '8065:8065'
    env_file:
      - .env
    restart: on-failure