name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Stop docker, delete app, create temp env, if directory exists, docker rmi
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} lexa@${{ secrets.SERVER_IP }} "\
          if [ -d /root/app/backapp ]; then \
              cd /root/app/backapp && \
              docker compose down && \
              rm -r /root/app/backapp; \
              DANG_IMG=$(docker images -f \"dangling=true\" -q) && \
              if [ -n \"$DANG_IMG\" ]; then \
                  docker rmi $DANG_IMG; \
              else \
                  echo 'No dangling images to remove.'; \
              fi; \
          else \
              echo 'Directory /root/app/backapp does not exist, creating it'; \
              mkdir -p /root/app/backapp; \
          fi"

      - name: Copy files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" ./ lexa@${{ secrets.SERVER_IP }}:/root/app/backapp

      - name: Create .env files
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} lexa@${{ secrets.SERVER_IP }} "\
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' > /root/app/backapp/.env && \
          echo 'DB_HOST=${{ secrets.DB_HOST }}' >> /root/app/backapp/.env && \
          echo 'SALT_PASSWORD=${{ secrets.SALT_PASSWORD }}' >> /root/app/backapp/.env
          echo 'SALT_JWT=${{ secrets.SALT_JWT }}' >> /root/app/backapp/.env"

      - name: Build docker compose
        run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} lexa@${{ secrets.SERVER_IP }} "cd /root/app/backapp && docker compose up -d --build"

      - name: Check Status and delete env
        run: |
            ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} lexa@${{ secrets.SERVER_IP }} "\
            cd /root/app/backapp && \
            docker compose ps && \
            truncate -s 0 .env"