name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" ./ lexa@${{ secrets.SERVER_IP }}:/root/app

      - name: Create and update .env file on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} user@${{ secrets.SERVER_IP }} "\
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' > /root/app/.env && \
          echo 'DB_HOST=${{ secrets.DB_HOST }}' >> /root/app/.env"

      - name: Deploy with Docker Compose
        run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} user@${{ secrets.SERVER_IP }} "cd /root/app && docker-compose up -d --build"


